### ISSUE TITLE
某些情况下 action-name 无法检索到指定技能

### ISSUE THREAD

**Issue by dragon-fish** [thewakingsands/cafe-kit#12]
https://github.com/thewakingsands/cafe-kit/blob/a93082157df94a85b8b862f49404c204b616f32b/pkgs/kit-tooltip/lib/CKAction.tsx#L79

我猜测这里的 `ClassJobLevel>0` 是为了过滤已弃用的技能，但是它也会会导致无法搜索到 ULK 和 BZY 的技能（例如“英杰的加护”），能否添加新的 attribute 以便手动指定允许搜索所有技能？

**Comment by oott123** [comment]
特殊技能可以用 id 指定，不用依赖搜索
